Eximius/urls.py
from unicodedata import name
from . import views
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings



urlpatterns = [
    path('admin/', admin.site.urls, name='Administration'),
    path('accounts/', include('accounts.urls')),
    path('', views.homepage, name='Home'),
    path('about/', views.about, name='About page'),
    path('patients/', include('articles.urls')),
    path('algorithms/', include('algorithm.urls')),
    path('genetic/', include('genetic.urls')),
]

accounts/urls.py
from unicodedata import name
from . import views
from django.urls import path, re_path


app_name ='accounts'

urlpatterns = [
    path('signup_p/',views.signup_view_p, name="signup_p"),
    path('patient_testlist/',views.patient_testlist, name="testlist"),
    path('signup_d/',views.signup_view_d, name="signup_d"),
    path('userhome_p/',views.patient_home, name="home_p"),
    path('userhome_d/',views.doctor_home, name="home_d"),
    path('login_patient/', views.login_view_p, name="login_patient"),
    path('login_doctor/', views.login_view_d, name="login_doctor"),
    path('login_admin/', views.login_view_a, name="login_admin"),
    path('logout/', views.logout_view, name="logout"),
    path('myaccount_p/<str:pk_test>/', views.myaccount_p, name="myaccount_p"),
    path('myaccount_d/<str:pk_test>/', views.myaccount_d, name="myaccount_d"),
    path('newsurgery/', views.surgery_create, name='new'),
    path('administration/', views.administration, name= 'administration'),
    path('administration_account/', views.administration_account, name= 'administration_account'),
    
]

Eximius/views.py
from django.http import HttpResponse
from django.shortcuts import render

def homepage(request):
    return render(request, 'homepage.html')

def about(request):
    return render(request, 'About.html')

Eximius/templates/About.html
{%extends 'base_layout.html'%}

{%block content%}
    <body>
        <h1>This text is the about page</h1>
        <p>welcome to Eximius Ruhuna</p>
    </body>
{%endblock%}

Eximius/templates/base_layout.html
{%load static%}

<html>
    <head>
        <meta charset="utf-8">
        <title>Homepage</title>
        <link rel="stylesheet" href="{%static 'style.css'%}">
        <link rel="stylesheet" href="{%static 'base_layout.css'%}">
        <link rel="stylesheet" href="{%static 'homepage.css'%}">
        <link rel="stylesheet" href="{%static 'login.css'%}">
        <link rel="stylesheet" href="{%static 'doctoraccount.css'%}">
        <link rel="stylesheet" href="{%static 'create_article.css'%}">
  
        <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">  
        <link rel="stylesheet" href="{% static 'https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.0/font/bootstrap-icons.css' %}">
        <script src="{% static 'js/bootstrap.min.js' %}"></script>   
    </head>
    <body>
         <header class="wrapper header-container">
            <h1><a href="{%url 'Home'%}">Eximius Ruhuna</a></h1>

        </header> 
        <div class="wrapper">
            {%block content%}
            {%endblock%}
        </div>
    </body>

</html>
    

Eximius/templates/homepage.html
{%extends 'base_layout.html'%}

{%block content%}
    <body class="homepage">
        

        <div class="container">
            <div class="left-container">
                {% comment %} includes the left image {% endcomment %}

            </div>
            <div class="right-container">
                {% comment %} Includes the content {% endcomment %}
                <h1>Dashboard</h1>
                <a type="button" id="homepage-btn" class="btn btn-outline-warning btn-lg" href="{%url 'accounts:login_patient'%}"> Patient</a>
                <a type="button" id="homepage-btn" class="btn btn-outline-warning btn-lg" href="{%url 'accounts:login_doctor'%}"> Doctor</a>
                <a type="button" id="homepage-btn" class="btn btn-outline-warning btn-lg" href="{%url 'accounts:administration'%}" > Administraion</a>
            </div>
        </div>
    </body>
{%endblock%}