Eximius/urls.py
from unicodedata import name
from . import views
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings



urlpatterns = [
    path('admin/', admin.site.urls, name='Administration'),
    path('accounts/', include('accounts.urls')),
    path('', views.homepage, name='Home'),
    path('about/', views.about, name='About page'),
    path('patients/', include('articles.urls')),
    path('algorithms/', include('algorithm.urls')),
    path('genetic/', include('genetic.urls')),
]

accounts/urls.py
from unicodedata import name
from . import views
from django.urls import path, re_path


app_name ='accounts'

urlpatterns = [
    path('signup_p/',views.signup_view_p, name="signup_p"),
    path('patient_testlist/',views.patient_testlist, name="testlist"),
    path('signup_d/',views.signup_view_d, name="signup_d"),
    path('userhome_p/',views.patient_home, name="home_p"),
    path('userhome_d/',views.doctor_home, name="home_d"),
    path('login_patient/', views.login_view_p, name="login_patient"),
    path('login_doctor/', views.login_view_d, name="login_doctor"),
    path('login_admin/', views.login_view_a, name="login_admin"),
    path('logout/', views.logout_view, name="logout"),
    path('myaccount_p/<str:pk_test>/', views.myaccount_p, name="myaccount_p"),
    path('myaccount_d/<str:pk_test>/', views.myaccount_d, name="myaccount_d"),
    path('newsurgery/', views.surgery_create, name='new'),
    path('administration/', views.administration, name= 'administration'),
    path('administration_account/', views.administration_account, name= 'administration_account'),
    
]

algorithm/urls.py
from unicodedata import name
from . import views
from django.contrib import admin
from django.urls import path, include,re_path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from unicodedata import name


app_name= 'algorithms'

urlpatterns = [
    path('ann/', views.fire_ann, name='ann'),
    re_path(r'^(?P<slug>[\w-]+)/$',views.patient_testdetail, name= "testdetail"),

]

articles/urls.py
from unicodedata import name
from . import views
from django.urls import path, re_path

app_name= 'patients'

urlpatterns = [
    path('', views.article_list, name='articles'),
    re_path(r'^(?P<slug>[\w-]+)/$',views.article_detail, name= "detail"),

]

genetic/urls.py
from unicodedata import name
from . import views
from django.contrib import admin
from django.urls import path, include,re_path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from unicodedata import name


app_name= 'genetic'

urlpatterns = [

    path('ga/', views.fire_genetic, name= 'genetic_a')

]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Patient_final(models.Model):
    user = models.OneToOneField(User, null=True, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    NIC = models.SlugField()
    age = models.IntegerField()
    gender = models.IntegerField()
    BMI = models.FloatField()
    situation = models.FloatField()
    seriousness = models.FloatField()
    surgery_type = models.IntegerField()
    time_slots = models.IntegerField()
    surgeons = models.IntegerField()
    urgancy = models.IntegerField()
    category = models.IntegerField()
    nature_of_surgery = models.IntegerField()
    date_of_visit_day = models.IntegerField()
    date_of_visit_month = models.IntegerField()
    date_of_visit_year = models.IntegerField()
    oparation_deadline_day = models.IntegerField()
    oparation_deadline_month = models.IntegerField()
    oparation_deadline_year = models.IntegerField()
    veto_days_day = models.IntegerField(null=True)
    veto_days_month = models.IntegerField(null=True)
    veto_days_year = models.IntegerField(null=True)
    surgery_time = models.FloatField()
    surgery_date_day = models.IntegerField()
    surgery_date_month = models.IntegerField()
    surgery_date_year = models.IntegerField()


    def __str__(self):
        return self.name

accounts/forms.py
from dataclasses import fields
from django.forms import ModelForm
from articles.models import Patient

class patient_form(ModelForm):
    class Meta:
        model = Patient
        fields = '__all__'

accounts/views.py
from audioop import reverse
#from crypt import methods
from operator import methodcaller
from unicodedata import name
from django.shortcuts import render, redirect, get_list_or_404
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login,logout
from articles.decorator import allowed_users
from articles.models import User, Patient
from django.contrib.auth.decorators import login_required 
from . import forms
from .models import Patient_final
from articles.models import Patient_duration, Patient_test
from .nurel import ann







def signup_view_p(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request,user)
            return render(request, 'accounts/verification.html')
    else:
        form = UserCreationForm()
    return render(request, 'accounts/signup_p.html', {'form': form})

def signup_view_d(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request,user)
            return render(request, 'accounts/verification.html')
    else:
        form = UserCreationForm()
    return render(request, 'accounts/signup_d.html', {'form': form})

@login_required(login_url="/accounts/login_patient/")
@allowed_users(allowed_groups=['Patient'])
def patient_home(request):
    return render(request, 'accounts/personalaccount.html')

@login_required(login_url="/accounts/login_doctor/")
@allowed_users(allowed_groups=['Doctor'])
def doctor_home(request):
    return render(request, 'accounts/doctoraccount.html')


def login_view_p(request):
    if request.method == 'POST':
        form=AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request,user)
            return redirect('accounts:home_p')
    else:
        form = AuthenticationForm()
    return render(request,'accounts/login_patient.html', {'form': form})

def login_view_d(request):
    if request.method == 'POST':
        form=AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request,user)
            return redirect('accounts:home_d')
    else:
        form = AuthenticationForm()
    return render(request,'accounts/login_doctor.html', {'form': form})


def logout_view(request):
    if request.method == 'POST':
        logout(request)
        return redirect( 'homepage.html')
#this
@login_required(login_url="/accounts/login_patient/")
@allowed_users(allowed_groups=['Patient'])
def myaccount_p(request,pk_test):
    user = User.objects.get(id=pk_test)
    context = {'user':user}
    return render(request, 'accounts/myaccount_p.html',context)

@login_required(login_url="/accounts/login_doctor/")
@allowed_users(allowed_groups=['Doctor'])
def myaccount_d(request,pk_test):
    user = User.objects.get(id=pk_test)
    context = {'user':user}
    return render(request, 'accounts/myaccount_d.html',context)

#@login_required(login_url="/accounts/login_doctor/")
#@allowed_users(allowed_groups=['Doctor'])
#def surgery_create(request):
#    if request.method == 'POST':
#        form=forms.patient_form(request.POST)
#        if form.is_valid:
#            form.save()
#            return redirect('algorithms:ann')
#    else:
#        form = forms.patient_form()
#    return render(request,'articles/article_create.html', {'form' : form})
#meka wenuwata pahalin demme function eka

@login_required(login_url="/accounts/login_doctor/")
@allowed_users(allowed_groups=['Doctor'])
def surgery_create(request):
    form=forms.patient_form(request.POST or None)
    if request.method == 'POST' and form.is_valid():
        data = form.cleaned_data
        print(data)
        age = data['age']
        #NIC= data['NIC']
        gender = data['gender']
        bmi = data['BMI']
        situation = data['situation']
        seriousness = data['seriousness']
        sur_type = data['surgery_type']
        print("nisal")
        predicted = ann(age,gender,bmi,situation,sur_type,seriousness)
        
        print(predicted)
        

        print(age)
        #print(NIC)
        #    form.save()
        #    return redirect('algorithms:ann')
    else:
        form = forms.patient_form()
    return render(request,'articles/article_create.html', {'form' : form})


def administration(request):
    return render(request, 'accounts/administration.html')


def login_view_a(request):
    if request.method == 'POST':
        form=AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request,user)
            return redirect('accounts:administration_account')
    else:
        form = AuthenticationForm()
    return render(request,'accounts/login_admin.html', {'form': form})

@login_required(login_url="/accounts/login_admin/")
@allowed_users(allowed_groups=['Admin'])
def administration_account(request):
    return render(request, 'accounts/administrationaccount.html')


@allowed_users(allowed_groups=['Doctor','Admin'])
def patient_testlist(request):
    patients = Patient_test.objects.all()
    return render(request,'accounts/Patient_testlist.html', {'Patients': patients})
    

accounts/templates/accounts/Patient_testlist.html
{%extends 'base_layout.html'%}

{%block content%}

    <body>
        <h1>List of surgeries</h1>
        <div class ="patients">
            {% for patient in Patients %}
                <div class = "patient">
                    <h2><a href="{%url 'algorithms:testdetail' slug=patient.NIC%}">{{patient.name}}</a></h2>
                    <p>{{patient.age}}</p>
                    <p>{{patient.NIC}}</p>
                    <p>{{patient.surgery_time}}</p>
                    
                </div>

            {% endfor %}
        </div>
        <p><a type="button" id="homepage-btn" class="btn btn-outline-warning btn-lg" href="{%url 'genetic:genetic_a'%}">Post Surgeries</a></p>
            
    </body>
{%endblock%}

accounts/templates/accounts/administration.html
{%extends 'base_layout.html'%}

{%block content%}
    <body class="homepage">
        

        <div class="container">
            <div class="left-container">
                {% comment %} includes the left image {% endcomment %}

            </div>
            <div class="right-container">
                {% comment %} Includes the content {% endcomment %}
                <h1>Dashboard</h1>
                <a type="button" id="homepage-btn" class="btn btn-outline-warning btn-lg" href="/admin" >Front End Administration</a>
                <a type="button" id="homepage-btn" class="btn btn-outline-warning btn-lg" href="{%url 'accounts:login_admin'%}"> Back End Administration</a>
            </div>
        </div>
    </body>
{%endblock%}

accounts/templates/accounts/administrationaccount.html
{%extends 'base_layout.html'%}

{%block content%}
<body>
    <h1>ADMINISTRATION</h1>
    <p><a type="button" id="homepage-btn" class="btn btn-outline-warning btn-lg" href="{%url 'accounts:testlist'%}">Temporary Surgeries</a></p>
    <p><a type="button" id="homepage-btn" class="btn btn-outline-warning btn-lg" href="{%url 'patients:articles'%}">Fixed Surgeries</a></p>
</body>
{%endblock%}

accounts/templates/accounts/doctoraccount.html
{%extends 'base_layout.html'%}
{% load bootstrap_icons %}

{%block content%}
<body class="homepage">
    

    <div class="container">
        <div class="left-container">
            {% comment %} includes the left image {% endcomment %}

        </div>
        <div class="right-container">
            {% comment %} Includes the content {% endcomment %}
            <h1>DOCTOR ACCOUNT</h1>
            <p><a type="button" id="homepage-btn" class="btn btn-outline-warning btn-lg" href="{%url 'accounts:myaccount_d' pk_test=user.id%}">{% bs_icon 'person-circle' %} My Account</a></p>
            <p><a type="button" id="homepage-btn" class="btn btn-outline-warning btn-lg" href="{%url 'patients:articles'%}">{% bs_icon 'activity' %} Surgeries</a></p>
            <p><a type="button" id="homepage-btn" class="btn btn-outline-warning btn-lg" href="{%url 'accounts:new'%}">{% bs_icon 'plus-circle' %} New Surgery</a></p>
        </div>
    </div>
</body>
{%endblock%}

accounts/templates/accounts/login.html
{%extends 'base_layout.html'%}

{%block content%}
<h1>Log In</h1>
<form class="site-form" action="{%url 'accounts:login'%}" method="post">
    {%csrf_token%}
    {{form}}
    <input type="submit" value="Login">
</form>
{%endblock%}

accounts/templates/accounts/login_admin.html
{%extends 'base_layout.html'%}

{% load crispy_forms_tags %}

{%block content%}


<div class="container-login">
    <div class="left-login-container">
        {% comment %} includes the left image {% endcomment %}

    </div>
    <div class="right-login-container">
        {% comment %} Includes the content {% endcomment %}

        <h1>Log In</h1>
        <form class="site-form" action="{%url 'accounts:login_admin'%}" method="post">
            {%csrf_token%}
            {{ form|crispy }}
            <input type="submit" id="login-btn" class="btn btn-outline-warning" value="Login">
        </form>
    </div>
</div>
{%endblock%}

accounts/templates/accounts/login_doctor.html
{%extends 'base_layout.html'%}

{% load crispy_forms_tags %}

{%block content%}


<div class="container-login">
    <div class="left-login-container">
        {% comment %} includes the left image {% endcomment %}

    </div>
    <div class="right-login-container">
        {% comment %} Includes the content {% endcomment %}

        <h1>Log In</h1>
        <form class="site-form" action="{%url 'accounts:login_doctor'%}" method="post">
            {%csrf_token%}
            {{ form|crispy }}
            <input type="submit" id="login-btn" class="btn btn-outline-warning" value="Login">
        </form>
        <h5>Don't have an account? Create an account</h5>
        <a type="button" id="login-btn" class="btn btn-outline-warning btn-lg" href="{%url 'accounts:signup_d'%}">Sign Up</a>
    </div>
</div>
{%endblock%}

accounts/templates/accounts/login_patient.html
{%extends 'base_layout.html'%}

{% load crispy_forms_tags %}

{%block content%}


<div class="container-login">
    <div class="left-login-container">
        {% comment %} includes the left image {% endcomment %}

    </div>
    <div class="right-login-container">
        {% comment %} Includes the content {% endcomment %}

        <h1>Log In</h1>
        <form class="site-form" action="{%url 'accounts:login_patient'%}" method="post">
            {%csrf_token%}
            {{ form|crispy }}
            <input type="submit" id="login-btn" class="btn btn-outline-warning" value="Login">
        </form>
        <h5>Don't have an account? Create an account</h5>
        <a type="button" id="login-btn" class="btn btn-outline-warning btn-lg" href="{%url 'accounts:signup_p'%}">Sign Up</a>
    </div>
</div>
{%endblock%}

accounts/templates/accounts/myaccount_d.html
{%extends 'base_layout.html'%}

{%block content%}
<body>
    <h1>DOCTOR ACCOUNT MY ACCOUNT</h1>
</body>
{%endblock%}

accounts/templates/accounts/myaccount_p.html
{%extends 'base_layout.html'%}

{%block content%}
<body>
    <h1>PATIENT ACCOUNT MY PERSONAL</h1>
</body>
{%endblock%}

accounts/templates/accounts/signup.html
{%extends 'base_layout.html'%}

{%block content%}
<h1>Sign up</h1>
<form class="site-form" action="/accounts/signup/" method="post">
    {%csrf_token%}
    {{form}}
    <input type="submit" value="Signup">
</form>
{%endblock%}

accounts/templates/accounts/signup_d.html
{%extends 'base_layout.html'%}

{% load crispy_forms_tags %}

{%block content%}


<div class="container-login">
    <div class="left-login-container">
        {% comment %} includes the left image {% endcomment %}

    </div>
    <div class="right-login-container">
        {% comment %} Includes the content {% endcomment %}

        <h1>Sign Up</h1>
        <form class="site-form" action="/accounts/signup_d/" method="post">
            {%csrf_token%}
            {{form|crispy}}
            <input type="submit" class="btn btn-outline-warning" value="Sign up">
        </form>
    </div>
</div>
{%endblock%}

accounts/templates/accounts/signup_p.html
{%extends 'base_layout.html'%}

{% load crispy_forms_tags %}

{%block content%}


<div class="container-login">
    <div class="left-login-container">
        {% comment %} includes the left image {% endcomment %}

    </div>
    <div class="right-login-container">
        {% comment %} Includes the content {% endcomment %}

        <h1>Sign Up</h1>
        <form class="site-form" action="/accounts/signup_p/" method="post">
            {%csrf_token%}
            {{form|crispy}}
            <input type="submit" class="btn btn-outline-warning" value="Sign up">
        </form>
    </div>
</div>
{%endblock%}

accounts/templates/accounts/verification.html
{%extends 'base_layout.html'%}

{%block content%}
<body>
    <h1>Thank you for signing up for the operation theatre management system. Please contact the Hospital adminisstration to get you account confirmed</h1>
</body>
{%endblock%}