Eximius/urls.py
from unicodedata import name
from . import views
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings



urlpatterns = [
    path('admin/', admin.site.urls, name='Administration'),
    path('accounts/', include('accounts.urls')),
    path('', views.homepage, name='Home'),
    path('about/', views.about, name='About page'),
    path('patients/', include('articles.urls')),
    path('algorithms/', include('algorithm.urls')),
    path('genetic/', include('genetic.urls')),
]

accounts/urls.py
from unicodedata import name
from . import views
from django.urls import path, re_path


app_name ='accounts'

urlpatterns = [
    path('signup_p/',views.signup_view_p, name="signup_p"),
    path('patient_testlist/',views.patient_testlist, name="testlist"),
    path('signup_d/',views.signup_view_d, name="signup_d"),
    path('userhome_p/',views.patient_home, name="home_p"),
    path('userhome_d/',views.doctor_home, name="home_d"),
    path('login_patient/', views.login_view_p, name="login_patient"),
    path('login_doctor/', views.login_view_d, name="login_doctor"),
    path('login_admin/', views.login_view_a, name="login_admin"),
    path('logout/', views.logout_view, name="logout"),
    path('myaccount_p/<str:pk_test>/', views.myaccount_p, name="myaccount_p"),
    path('myaccount_d/<str:pk_test>/', views.myaccount_d, name="myaccount_d"),
    path('newsurgery/', views.surgery_create, name='new'),
    path('administration/', views.administration, name= 'administration'),
    path('administration_account/', views.administration_account, name= 'administration_account'),
    
]

articles/urls.py
from unicodedata import name
from . import views
from django.urls import path, re_path

app_name= 'patients'

urlpatterns = [
    path('', views.article_list, name='articles'),
    re_path(r'^(?P<slug>[\w-]+)/$',views.article_detail, name= "detail"),

]

articles/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class Patient(models.Model):
    user = models.OneToOneField(User, null=True, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    NIC = models.SlugField()
    age = models.IntegerField()
    gender = models.IntegerField()
    BMI = models.FloatField()
    situation = models.FloatField()
    seriousness = models.FloatField()
    surgery_type = models.IntegerField()
    time_slots = models.IntegerField()
    surgeons = models.IntegerField()
    urgancy = models.IntegerField()
    category = models.IntegerField()
    nature_of_surgery = models.IntegerField()
    date_of_visit_day = models.IntegerField()
    date_of_visit_month = models.IntegerField()
    date_of_visit_year = models.IntegerField()
    oparation_deadline_day = models.IntegerField()
    oparation_deadline_month = models.IntegerField()
    oparation_deadline_year = models.IntegerField()
    veto_days_day = models.IntegerField(null=True)
    veto_days_month = models.IntegerField(null=True)
    veto_days_year = models.IntegerField(null=True)




    def __str__(self):
        return self.name


class Patient_duration(models.Model):
    user = models.OneToOneField(User, null=True, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    NIC = models.SlugField()
    age = models.IntegerField()
    gender = models.IntegerField()
    BMI = models.FloatField()
    situation = models.FloatField()
    seriousness = models.FloatField()
    surgery_type = models.IntegerField()
    time_slots = models.IntegerField()
    surgeons = models.IntegerField()
    urgancy = models.IntegerField()
    category = models.IntegerField()
    nature_of_surgery = models.IntegerField()
    date_of_visit_day = models.IntegerField()
    date_of_visit_month = models.IntegerField()
    date_of_visit_year = models.IntegerField()
    oparation_deadline_day = models.IntegerField()
    oparation_deadline_month = models.IntegerField()
    oparation_deadline_year = models.IntegerField()
    veto_days_day = models.IntegerField(null=True)
    veto_days_month = models.IntegerField(null=True)
    veto_days_year = models.IntegerField(null=True)
    surgery_time = models.FloatField()


    def __str__(self):
        return self.name


class Patient_test(models.Model):
    user = models.OneToOneField(User, null=True, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    NIC = models.SlugField()
    age = models.IntegerField()
    gender = models.IntegerField()
    BMI = models.FloatField()
    situation = models.FloatField()
    seriousness = models.FloatField()
    surgery_type = models.IntegerField()
    time_slots = models.IntegerField()
    surgeons = models.IntegerField()
    urgancy = models.IntegerField()
    category = models.IntegerField()
    nature_of_surgery = models.IntegerField()
    date_of_visit_day = models.IntegerField()
    date_of_visit_month = models.IntegerField()
    date_of_visit_year = models.IntegerField()
    oparation_deadline_day = models.IntegerField()
    oparation_deadline_month = models.IntegerField()
    oparation_deadline_year = models.IntegerField()
    veto_days_day = models.IntegerField(null=True)
    veto_days_month = models.IntegerField(null=True)
    veto_days_year = models.IntegerField(null=True)
    surgery_time = models.FloatField()
    surgery_date_day = models.IntegerField()
    surgery_date_month = models.IntegerField()
    surgery_date_year = models.IntegerField()


    def __str__(self):
        return self.name

articles/views.py
from datetime import date
from django.http import HttpResponse, request
from django.shortcuts import render
from .models import Patient
from django.contrib.auth.decorators import login_required
from .decorator import allowed_users
from accounts.models import Patient_final


@login_required(login_url="/accounts/login_doctor/")
@allowed_users(allowed_groups=['Doctor','Admin'])
def article_list(request):
    patients = Patient_final.objects.all()
    return render(request,'articles/article_list.html', {'Patients': patients})

@login_required(login_url="/accounts/login_doctor/")
@allowed_users(allowed_groups=['Doctor','Admin'])
def article_detail(request, slug):
    #return HttpResponse(slug)
    patients = Patient_final.objects.get(NIC=slug)
    return render(request, 'articles/patient_detail.html', {'Patient': patients})


# Create your views here.

articles/templates/articles/article_create.html
{%extends 'base_layout.html'%}

{% load crispy_forms_tags %}

{%block content%}
<body class="homepage">
    <div class="create-article">
        <div class="article-content">
        <h2>Surgery Information</h2>
        <form action="{%url 'accounts:new'%}" method="POST">
            {%csrf_token%}
            {{form|crispy}}
            <br>
            <input class="btn btn-outline-warning btn-lg" type="reset" name="Reset">
            <input class="btn btn-outline-warning btn-lg" type="submit" name="Submit">
            
        </form>
    </div>

    </div>
</body>
{%endblock%}

articles/templates/articles/article_list.html
{%extends 'base_layout.html'%}

{%block content%}

    <body>
        <h1>List of surgeries</h1>
        <div class ="patients">
            {% for patient in Patients %}
                <div class = "patient">
                    <h2><a href="{%url 'patients:detail' slug=patient.NIC%}">{{patient.name}}</a></h2>
                    <p>{{patient.age}}</p>
                    <p>{{patient.NIC}}</p>
                    <p>{{patient.surgery_date_day}}/{{patient.surgery_date_month}}/{{patient.surgery_date_year}}</p>
                    <p>{{patient.surgery_time}}</p>
                    
                </div>

            {% endfor %}
        </div>
            
    </body>
{%endblock%}

articles/templates/articles/patient_detail.html
{%extends 'base_layout.html'%}

{%block content%}
<div class="patient-details">
    <div class="patient">
        <h2>Name : {{Patient.name}}</h2>
        <p>Age : {{Patient.age}}</p>
        <p>NIC : {{Patient.NIC}}</p>
        <p>Gender : {{Patient.gender}}</p>
        <p>BMI : {{Patient.BMI}}</p>
        <p>Situation : {{Patient.situation}}</p>
        <p>Seriousness : {{Patient.seriousness}}</p>
        <p>Surgery type : {{Patient.surgery_type}}</p>
        <p>Time slots : {{Patient.time_slots}}</p>
        <p>Urgancy : {{Patient.urgancy}}</p>
        <p>Category : {{Patient.category}}</p>
        <p>Nature of surgery : {{Patient.nature_of_surgery}}</p>
        <p>Surgery time : {{Patient.surgery_time}}</p>
        <p>Date of visit : {{Patient.date_of_visit_day}}/{{Patient.date_of_visit_month}}/{{Patient.date_of_visit_year}}</p>
        <p>Oparation deadline : {{Patient.oparation_deadline_day}}/{{Patient.oparation_deadline_month}}/{{Patient.oparation_deadline_year}}</p>
        <p>Veto days : {{Patient.veto_days_day}}/{{Patient.veto_days_month}}/{{Patient.veto_days_year}}</p>
        <p>Surgery date : {{Patient.surgery_date_day}}/{{Patient.surgery_date_month}}/{{Patient.surgery_date_year}}</p>


    </div>
</div>
{%endblock%}